import Head from "next/head";
import Form from "../components/Form";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <main className=" min-w-max mx-auto">
      <Form />
      </main>
    </div>
  );
}
